version: "3.8"

services:
  app:
    build: .
    image: gsong/django-postgres
    container_name: edb-app
    hostname: app
    depends_on:
      - db
    environment:
      APP_PORT: ${APP_PORT:-5000}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-demo}
    command: bin/start-dev-server.sh
    init: true
    volumes:
      - ./.data/services/app/bash_history:/root/.bash_history
      - ./.data/services/app/ipython/:/root/.ipython
      - .:/var/projects
    ports:
      - "${APP_PORT:-5000}:${APP_PORT:-5000}"

  db:
    image: postgres:13-alpine
    container_name: edb-db
    hostname: db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-demo}
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres || exit 1
    stop_grace_period: 1m
